### ISSUE TITLE
Gen VIII inclusion

### ISSUE THREAD

**Issue by elesafan85** [Menardi/whosthatpokemon#10]
I understand that all of the images required haven't been released on bulbapedia, which is where you source them from, but once they are, will you be updating the site to include the pokemon of Generation 8?

**Comment by Menardi** [comment]
Yes, I will be including Gen 8 some time over the next few weeks, once Bulbapedia is fully up to date. It looks like it's already mostly complete, so it shouldn't be too long.

**Comment by gabrigois** [comment]
Do you have any expected date?

**Comment by Menardi** [comment]
I checked yesterday, and all of the artwork images are now available on Bulbapedia. However, there are no sprites in Gen 8 (for Ultra and Master modes), and I cannot find any of the cries yet either. I am considering proceeding with just the artwork images for now, but it will require quite a bit of development work to adapt the game to work without the cries or sprites. So I think it is likely to be another few weeks yet unfortunately.

**Comment by gabrigois** [comment]
Any progress? Really looking forward to it

**Comment by Menardi** [comment]
I have just updated Who's That Pokémon to add support for Generation 8! I've added the artwork (for Easy and Normal difficulties), and the cries (for Elite difficulty). However, I do not think any official sprites exist for this generation, because Sword and Shield are fully 3D games. As a result, Gen 8 won't work with Master and Ultra difficulties.

Do let me know if you come across any issues as a result of this update!
