### ISSUE TITLE
The nature of auto complete in forgiving

### ISSUE THREAD

**Issue by IzacLess** [Menardi/whosthatpokemon#25]
Love this game, I play it nearly every night to help get to sleep. My streak on All gens - Normal - Forgiving is 64 which I'm quite proud of.
I love the forgiving spelling setting (thought I swear its more strict on earlier gens than later), but I don't love that because it often auto-completes the name while I'm mid typing, I'll type extra letters on the end of the name because the text box is still live after the answer is correct. Would be great if the text field was locked when the correct name was entered, so it doesn't read 'Oddishsh' or 'Phantumpum' etc.

**Comment by Menardi** [comment]
Thanks for your feedback! The forgiving spelling uses a relatively basic algorithm called a [soundex](https://en.wikipedia.org/wiki/Soundex), which treats similar-sounding letters as being identical (like `b / p` or `c / k`), and ignores vowels altogether. If it seems more strict on earlier generations, it might just be because the names have more different-sounding letters than later generations!

Regarding the continued typing after a correct answer, there is actually already code in the app to prevent this from happening. I've just tested it in a Chrome, Safari and Firefox on desktop and mobile, and it does stop me from typing after a correct answer. This might be a browser-specific issue, which browser are you using?

**Comment by IzacLess** [comment]
Now that I'm paying more attention to the way the forgiving spelling works you're (obviously) right. It's super cool.

I'm on Chrome on Android, still getting the issue of being able to type after correct answer.

Not sure if there was an update, but previously when playing the current score and time on last answer overlay never displayed while the keyboard was on screen on mobile. But now the overlay is visible during play, which is great.

**Comment by Menardi** [comment]
I finally had some time to look into this more, and was able to reproduce the continued typing. It seems to be a bug in Chrome on Android, because it works as expected in every other browser, including Chrome on desktop. I've added a workaround for now, so extra typing after a correct answer in Chrome on Android has no effect.

**Comment by IzacLess** [comment]
Fantastic. Its fixed at my end. And the bug there the keyboard popping up
pushed the image half off the screen to the top is also fixed. Though I did
enjoy the hard mode of only seeing half of the image haha

**Comment by Menardi** [comment]
Oh yeah, that was another thing I fixed while looking into this issue. It turned out that right around the time you posted this issue last year, Chrome on Android changed its default behaviour when the keyboard is opened, which caused things to move off screen. It should all align just right now!
