### ISSUE TITLE
does not display the correctness of the answer

### ISSUE THREAD

**Issue by samruddhishinde20003** [Menardi/whosthatpokemon#39]
It doesn't display anything when the guess made is wrong and also a little ambiguous for the users while submitting the answer .
I recommend adding a submit button and display if it's wrong answer for making it user friendly.

**Comment by Menardi** [comment]
Thanks for your feedback. The text input has worked like this since I first launched it several years ago, so I don't want to make any changes, as so many users are familiar with how it works already. I'm going to close this, as I have no plans to change it. I hope you'll get used to not having a submit button!
