### ISSUE TITLE
Don't use gross upscaling on pixel sprites

### ISSUE THREAD

**Issue by pressRtowin** [Menardi/whosthatpokemon#49]
What the title says. Pixel art should be scaled with nearest neighbor.

**Comment by Menardi** [comment]
The scaling of the images is handled by the browser and I don't have a huge amount of control over it. The images are drawn to a `canvas` element at exactly four times their file resolution, to ensure we're not introducing any subpixel rendering. It's up to the browser to figure out how to scale it from there.

In the most recent update, I did change some settings to suggest to the browser that these sprites shouldn't get image smoothing, and I think it does look a lot better. From here, it could be down to the browser's specific implementation or even how the OS renders to screen.

If you have any specific suggestions of improvements that could be made in the code, I'm happy to take a look at any pull requests that would improve this.

**Comment by Menardi** [comment]
Thanks for the PR! I think I originally tested `image-rendering: crisp-edges`, but it turns out it has poor support. `image-rendering: pixelated` works much better, thanks for the suggestion. I'm deploying a fix now.

**Comment by Menardi** [comment]
Good spot! It seems the Gen 6 and 7 sprite images were all 256x256, with a lot of transparent padding around them. I've cropped them with ImageMagick, making the smaller sprites 96x96 to match the other generations. Some were too big to fit in that space, so I've made them the minimum square size possible without rescaling them.

I've also updated the canvas scaling code to use a dynamic multiplier based on the sprite size, rather than always multiplying by 4 (in b8ae040). This should fix the issue.

**Comment by Menardi** [comment]
Whoops, sorry for the scare! :joy: The code was only checking if the image's width was less than 200px to determine if it was a sprite, and Kakuna happens to be a particularly narrow Pokémon at 189px, so the game treated it as a sprite.

I've fixed this in ee0c235 by now checking for the larger of width and height when doing the comparison. Thanks for the bug report!
